apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-scaledobject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiagat/argocd-sandbox
    path: charts/keda-scaledobject
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
