apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-add-ons-http
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  source:
    chart: keda-add-ons-http
    repoURL: https://kedacore.github.io/charts
    targetRevision: 0.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
