apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inflate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inflate
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        query: scaler_gauge
        threshold: "5"
        activationThreshold: "0"
