apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inflate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inflate
  pollingInterval: 300
  minReplicaCount: 0
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        query: sum(up{container="cert-manager-controller"})
        threshold: "1000"
        activationThreshold: "0"
        ignoreNullValues: "true"
