apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler-metrics
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
      labels:
        app: scaler-metrics
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: scaler
          image: tiagat/scaler:latest
          resources:
            requests:
              cpu: 0.25
          ports:
            - containerPort: 3000
              name: http
