apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-scaledobject
spec:
  replicas: 0
  selector:
    matchLabels:
      app: keda-scaledobject
  template:
    metadata:
      labels:
        app: keda-scaledobject
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: keda-scaledobject
          image: keda-scaledobject

