apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaledobject
  annotations:
    autoscaling.keda.sh/paused: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-scaledobject
  pollingInterval: 300
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: up
        query: sum(up{container="nonexist-container"})
        threshold: "1000"
        activationThreshold: "0"
        ignoreNullValues: "true"
